Mot so tim hieu ve mang may tinh
cloudcomputinghust/openstack-manual pull request #13
Opened 2017-03-24 10:21 UTC by Monlight

2017-03-24 12:23 UTC, hieulq requested changes
- xoá file pdf, viết dạng markdown
- file readme viết sai chính tả (reame)

2017-03-24 13:30 UTC, Monlight commented
Vâng ạ.

2017-03-24 19:23 GMT+07:00 Hieu LE <notifications@github.com>:

> *@hieulq* requested changes on this pull request.
>
>    - xoá file pdf, viết dạng markdown
>    - file readme viết sai chính tả (reame)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HPCC-Cloud-Computing/hpcc-know-how/pull/13#pullrequestreview-28890208>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARlivuKKWmwCVaaQY5OEnuB1ztziJPkkks5ro7XbgaJpZM4MoCR1>
> .
>

2017-03-25 16:16 UTC, hieulq requested changes
vẫn chưa có gì thay đổi so với commit trước nhé

2017-03-27 17:55 UTC, hieulq requested changes
Bài viết tốt, đôi chỗ còn chưa chính xác, @haminhcong đã review lại chưa đấy?

File readme chưa fix hết typo name.
Xoá file pdf đi em.

2017-03-28 01:36 UTC, haminhcong commented
@hieulq Em review bài viết trên facebook rồi ạ.

2017-03-30 12:40 UTC, hieulq requested changes
vẫn chưa sửa lại các lỗi typo
@haminhcong em có tutor cho các bạn không?

2017-03-30 12:42 UTC, haminhcong commented
em có tutor cho 2 em K59 rồi ạ. Hôm đấy em còn lấy cả ví dụ ra vở cho mấy đứa rồi mà :(

2017-03-30 12:44 UTC, haminhcong commented
Có thể là 2 đứa chưa vào check mail, nên không thấy request change trên github của anh.

2017-03-31 01:19 UTC, hieulq requested changes

2017-03-31 01:19 UTC, hieulq commented on K59/Nguyen-Tien-Thao/REAME.md
> +# K59 Repo
typo về tên file

2017-03-31 02:10 UTC, hieulq requested changes

2017-03-31 02:10 UTC, hieulq commented on K59/Nguyen-Tien-Thao/REAME.md
> +# K59 Repo
tại sao vẫn còn file này?

2017-03-31 06:15 UTC, sunlu1996 reviewed
Em sửa lại rồi ạ, anh xem lại hộ em với ạ.

2017-03-31 06:15 UTC, sunlu1996 commented on K59/Nguyen-Tien-Thao/REAME.md
> +# K59 Repo
Em sửa lại rồi ạ, anh xem lại hộ em ạ.

2017-03-31 06:19 UTC, hieulq approved these changes

2017-03-31 06:19 UTC, merged

2017-03-31 08:53 UTC, haminhcong reviewed
Review git document

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Git là một trong những hệ thống quản lý phiên bản phân tán (VCS)
Không dịch word by word. viết rõ ra VCS nó là cái gì. Em chưa viết từ đầy đủ mà em đã dùng từ viết tắt ?

Giải thích hệ thống quản lý phiên bản - version control là gì ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Git khác với các VCS khác ở chỗ Git "nghĩ" về dữ liệu.Phần lớn các hệ thống VCS khác lưu trữ thông tin dưới dạng danh sách các tập tin được thay đổi. Các hệ thống này (CVS, Subversion, Perforce, Baza
Không dịch word by word.

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Trong khi Git coi dữ liệu của mình giống như 1 tập các ảnh của một hệ thống tập tin nhỏ. Việc commit hay lưu lại trạng thái hiện tại của dự án được Git chụp lại một bức ảnh, bức ảnh đó ghi lại nội du
Giải thích cho anh một commit là gì ? Một commit bao gồm những thành phần con là gì ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Ba trạng thái của Git gồm: Modified, Staded, Commit.Committed có nghĩa là dữ liệu đã được lưu trữ một cách an toàn trong cơ sở dữ liệu. Modified có nghĩa là bạn đã thay đổi tập tin nhưng chưa commit
typo

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Ba trạng thái của Git gồm: Modified, Staded, Commit.Committed có nghĩa là dữ liệu đã được lưu trữ một cách an toàn trong cơ sở dữ liệu. Modified có nghĩa là bạn đã thay đổi tập tin nhưng chưa commit
3 trạng thái của git? hay 3 trạng thái của một tệp tin được git quản lý - theo dõi ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> ++ Staged <-> Khu vực tổ chức
Không dịch word by word.

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +
Kiểm tra lại chỗ này. Có phải là git directory hay là .git directory ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Thư mục Git là nơi Git lưu trữ các "siêu dữ kiện" (metadata) và cơ sở dữ liệu cho dự án của bạn. Đây là phần quan trọng nhất của Git, nó là phần được sao lưu về khi bạn tạo một bản sao (clone) của mộ
"siêu dữ kiện" ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Khu vực khán đài là một tập tin đơn giản được chứa trong thư mục Git, nó chứa thông tin về những gì sẽ được commit trong lần commit sắp tới. Nó còn được biết đến với cái tên "chỉ mục" (index), nhưng
Khu vực khán đài @Monlight dùng google translate à ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +
check lại xem có phải thư mục Git hay không ?

Một lần nữa, không word by word.

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Ba trạng thái của Git gồm: Modified, Staded, Commit.Committed có nghĩa là dữ liệu đã được lưu trữ một cách an toàn trong cơ sở dữ liệu. Modified có nghĩa là bạn đã thay đổi tập tin nhưng chưa commit
Sao lại có chỗ là commit, chỗ lại là commited ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Ba trạng thái của Git gồm: Modified, Staded, Commit.Committed có nghĩa là dữ liệu đã được lưu trữ một cách an toàn trong cơ sở dữ liệu. Modified có nghĩa là bạn đã thay đổi tập tin nhưng chưa commit
"Và staged là bạn đã đánh dấu sẽ commit phiên bản hiện tại của một tập tin đã chỉnh sửa trong lần commit sắp tới" Chỗ này chưa rõ nghĩa

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +![h2](http://i.imgur.com/Lth9CPR.png)
Sao ở trên là Modified, Staged, Commited mà ở dưới lại thành unmodified, Modified, staged ?

Hình vẽ sai flow rồi, kiểm tra lại. Mà sao cả 2 đứa sai cùng 1 chỗ y hệt nhau thế này ? Nguồn của cái hình này lấy ở đâu ra ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Khi đó README.md đã được stage và nó nằm trong danh sách các thay đổi chuẩn bị commit, nếu bạn tiến hành commit thì Git sẽ chụp bức ảnh mới để lưu lại phiên bản này, và README.md sẽ trở về trạng thái
stage ? Typo

danh sách các thay đổi chuẩn bị commit ? "Chuẩn bị" hay là "chuẩn bị được"

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Khi đó README.md đã được stage và nó nằm trong danh sách các thay đổi chuẩn bị commit, nếu bạn tiến hành commit thì Git sẽ chụp bức ảnh mới để lưu lại phiên bản này, và README.md sẽ trở về trạng thái
README.md sẽ trở về trạng thái unmodified.
README.md đã ở trạng thái unmodified lúc nào đâu mà nói nó trở về ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Bạn có thể dùng vim, sau đó xem lại trạng thái của README.md:
Câu này:

Bạn có thể dùng vim, sau đó xem lại trạng thái của README.md:

Em có thể thay bằng câu: 

Sau khi thay đổi nội dung của flie README.md, bạn có thể xem lại trạng thái của file này:

Viết như thế này sẽ rõ ràng hơn, người đọc cũng dễ hiểu hơn đúng không ?

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +- Không hề, Git sẽ không lưu cho bạn đâu và kết quả là tập README.md của bạn sẽ chẳng có thay đổi gì cả bởi vì Git tổ chức tập tin chính là lúc bạn chạy lệnh ' git add '
Ví dụ chưa rõ ràng, lấy lại một ví dụ cụ thể

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +Commit là để lưu lại dữ liệu của file vào cơ sở dữ liệu của máy bạn.
Commit là để lưu lại dữ liệu của file vào cơ sở dữ liệu của máy bạn. 
Chỗ này chưa chính xác, kiểm tra lại định nghĩa commit cho anh.

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> +- Hỏi thông minh thế? -Câu trả lời của Git là "lối tắt". Bạn cần thêm cờ  -a  khi thực hiện ' git commit '. Git sẽ tự động thêm theo dõi cho tất cả các tập tin của bạn trước khi thực hiện commit (như
Không viết báo cáo theo kiểu "teen style" vào báo cáo cho người lớn:
"Hỏi thông minh thế?"

Viết lại chỗ này.

2017-03-31 08:53 UTC, haminhcong commented on K59/Nguyen-Van-Sang/git/basic_git.md
> + >$ git mv file01.md newfile.md
Không up ảnh lên cái trang aloxo.vn nữa. Một là dùng ảnh local, hai là up ảnh lên cái trang nào không chèn watermark.