first commit
cloudcomputinghust/openstack-manual pull request #14
Opened 2017-03-24 10:21 UTC by NTT-TNN

2017-03-24 12:24 UTC, hieulq requested changes
file readme sai typo ở tên file

2017-03-30 12:41 UTC, hieulq requested changes
chưa sửa lại typo trong tên file, repo sẽ ko hiển thị nội dung default file README.md

2017-03-30 12:50 UTC, hieulq requested changes
1. Tên file và folder ko nên có whitespace hoặc ký tự đặc biệt
2. Đã dùng markdown thì ko đẩy pdf hay doc hay bất cứ file binary nào lên
3. 2 tuần rồi vẫn chưa rename được cái tên file README.md bị sai

@haminhcong xem lại cách truyền đạt, nói lại với các em ấy về git diff, git log, git show và xem các thay đổi trên từng commit hoặc pull requests của github

2017-03-30 12:50 UTC, hieulq commented on K59/Nguyen-Tien-Thao/REAME.md
> +# K59 Repo
typo ở tên file này

2017-03-30 12:50 UTC, hieulq commented on K59/Nguyen-Van-Sang/REAME.md
> +# K59 Repo
ditto

2017-03-30 12:50 UTC, hieulq commented on K59/REAME.md
> +# K59 Repo
ditto

2017-03-30 13:01 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/REAME.md
> +# K59 Repo
Dạ vâng e đang fix ạ

2017-03-30 13:05 UTC, hieulq requested changes

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +# Basic Git
file name vẫn còn white space

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +Mặc dù khu vực tổ chức là một cách làm việc hay nhưng đôi khi chúng khiến quy trình làm việc trở nên phức tạp. Nếu bạn muốn bỏ qua bước này git cung cấp sắn cho bạn một lỗi tắt. Chỉ cần thêm `-a` vào
khu vực tổ chức? @haminhcong review lại đoạn này

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +
commit sau bổ sung thêm về cherry-pick và rebase trong git

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +### 3. Tạo một kho chứ git
typo

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +Có hai cách để tạo một kho chứ git
typo tiếp

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +
còn git merge và cơ chế chia branch trong git?

2017-03-30 13:05 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan 1. Mang may tinh.md
> +| Tần vật lý | Chuyển dữ liệu **thành tín hiệu và truyền** |
typo

2017-03-30 13:09 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +
Dạ vâng a.

2017-03-30 13:10 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +
Em chưa kịp dịch phần đó e tính tuần sau e sẽ làm a ạ

2017-03-30 13:13 UTC, hieulq commented
Vậy cứ hoàn thiện nốt phần này đã, anh merge xong thì tuần sau đẩy pull request khác.

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/CM/IT/M/MU d-@? s+(++):+(++) !a C++++(++++)$ ULC++++(++)$ P L++(+++)$ E !W N* o+ K w O- M V- PS+ PE++ Y+ PGP+ t 5 X R tv+ b+(++)>+++ DI- D+ G e++(+++) h-- r(++)>+++ y-
------END GEEK CODE BLOCK------

On Mar 30, 2017, 20:10 +0700, Nguyễn Tiến Thạo <notifications@github.com>, wrote:
>
> @NTT-TNN commented on this pull request.
>
>
> In K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md (https://github.com/HPCC-Cloud-Computing/hpcc-know-how/pull/14#discussion_r108920978):
>
> > + (use "git checkout -- <file>..." to discard changes in working directory) + +modified: Tuan 2/Tuan 2. Git_Basic.md +deleted: test.txt + +no changes added to commit (use "git add" and/or "git commit -a") + +``` + +Git cũng có chức năng cho phép bạn giữ một file trong thư mục làm việc mà không đưa vào khu vực stage(không muốn theo dõi nó): +`$ git rm --cached readme.txt` + + + + +
>
> Em chưa kịp dịch phần đó e tính tuần sau e sẽ làm a ạ
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub (https://github.com/HPCC-Cloud-Computing/hpcc-know-how/pull/14#discussion_r108920978), or mute the thread (https://github.com/notifications/unsubscribe-auth/ABui7uxhi4D4hT0LKX7sBDTB0Ahn-kD2ks5rq6mwgaJpZM4MoCR6).
>
>
>

2017-03-30 15:41 UTC, hieulq requested changes

2017-03-30 15:41 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_1. Mang_may_tinh.md
> +# Mạng máy tính
xoá whitespace nốt file này là merge thôi :)

2017-03-30 15:52 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_1. Mang_may_tinh.md
> +# Mạng máy tính
ok a e sửa ngay đây

2017-03-30 16:33 UTC, merged

2017-03-30 16:37 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +Mặc dù khu vực tổ chức là một cách làm việc hay nhưng đôi khi chúng khiến quy trình làm việc trở nên phức tạp. Nếu bạn muốn bỏ qua bước này git cung cấp sắn cho bạn một lỗi tắt. Chỉ cần thêm `-a` vào
@NTT-TNN Khu vực tổ chức ở đây là gì trong tiếng anh vậy em ? Stagging area hay là working directory ?

Nếu có một số từ tiếng Anh mà chuyển sang tiếng Việt không sát nghĩa thì em cứ bê nguyên từ tiếng Anh sang nhé, không cần phải bê tất cả các từ tiếng Anh sang tiếng Việt đâu, vì có nhiều từ trong tiếng Anh không có từ tương đương trong tiếng Việt.

2017-03-30 16:37 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_1. Mang_may_tinh.md
> +# Mạng máy tính
@NTT-TNN Thạo nói chuyện với anh Hiếu, cũng như các anh, các bạn trên trung tâm thì không nên viết tắt nhé.

2017-03-30 16:38 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +Mặc dù khu vực tổ chức là một cách làm việc hay nhưng đôi khi chúng khiến quy trình làm việc trở nên phức tạp. Nếu bạn muốn bỏ qua bước này git cung cấp sắn cho bạn một lỗi tắt. Chỉ cần thêm `-a` vào
stagging area anh

2017-03-30 16:50 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan 2. Git_Basic.md
> +Mặc dù khu vực tổ chức là một cách làm việc hay nhưng đôi khi chúng khiến quy trình làm việc trở nên phức tạp. Nếu bạn muốn bỏ qua bước này git cung cấp sắn cho bạn một lỗi tắt. Chỉ cần thêm `-a` vào
Stagging Area nếu như dịch ra tiếng việt thì sẽ là danh từ " khu vực chứa các file đã được theo dõi - tracked"

Cơ mà từ này với từ Working directory, theo anh thì cứ để nguyên tiếng Anh đi, không nên dịch 2 từ này sang tiếng Việt.

2017-03-31 02:12 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_1. Mang_may_tinh.md
> +# Mạng máy tính
@haminhcong @NTT-TNN viết tắt thoải mái, anh không câu nệ cái này, miễn sao viết tắt anh hiểu là được.

2017-03-31 04:41 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +
Chương 1 của em có tên là : Git là gi ?
Nhưng anh đọc hết chương 1 vẫn chưa thấy em mô tả git là gì ở chỗ nào.

2017-03-31 06:27 UTC, haminhcong reviewed
Review git document

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +#### 2.2 Ba trạng thái của Git
3 trạng thái của hệ thống git hay là 3 trạng thái của 1 tệp tin nằm trong project do Git quản lý ?

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +Tương ứng với ba trạng thái là ba phần riêng biệt của một dự án sử dụng Git:
Giữ nguyên từ project thay vì dịch nó sang từ "dự án" nhé, cái từ dự án không sát nghĩa với từ project lắm

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +
Dùng từ thư mục git chưa được chính xác lắm. Chính xác thì nó là  **thư mục .git**, hay còn gọi là **.git directory**.

Cái này em ls -al cái project của em thì sẽ thấy nó.

Chú thích thêm bên cạnh cái thư mục làm việc là working directory để người đọc dễ hiểu hơn nhé. 

"phiên làm việc của dự án" có nghĩa là gì ?

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +- Bạn commit ảnh của các tệp tin trong khu vực staged sẽ được lưu trữ vĩnh viện vào thư mục git. Tương ứng với câu lệnh :`Git commit -m "status"`
Typo

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +### 3. Tạo một kho chứa git
Typo

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +- Bạn commit ảnh của các tệp tin trong khu vực staged sẽ được lưu trữ vĩnh viện vào thư mục git. Tương ứng với câu lệnh :`Git commit -m "status"`
"Ảnh của các tệp tin" là gì ?
Phần này chưa ổn, trình bày lại cho anh 3 cái tiến trình công việc cơ bản của git.

Trình bày thêm cho anh về  commit trong git ?

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +Để theo dõi một tệp tin mới bạn sẽ sử dụng lệnh `git add <teentfile>` khi đó file sẽ đưa vào khu vực staging và sẽ được commit vào thư mục git tại lần commit sau.
typo

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +##### **Bỏ qua khu vực tổ chức:**
Không dịch word by word nữa. Hoặc dùng từ tiếng Việt tương đương nghĩa, hoặc bê luôn từ tiếng Anh vào.

2017-03-31 06:27 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +
Lấy cho anh ví dụ cụ thể về một file trong hệ thống git khi nó đi qua 4 trạng thái.

2017-03-31 07:48 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +#### 2.2 Ba trạng thái của Git
Ba trạng thái của một tệp tin trong project Git. Em sẽ fix ạ.

2017-03-31 07:48 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +Tương ứng với ba trạng thái là ba phần riêng biệt của một dự án sử dụng Git:
OK anh

2017-03-31 07:49 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +
Phiên làm việc là một lần làm việc ý anh.

2017-03-31 07:50 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +- Bạn commit ảnh của các tệp tin trong khu vực staged sẽ được lưu trữ vĩnh viện vào thư mục git. Tương ứng với câu lệnh :`Git commit -m "status"`
em sẽ update lại ạ

2017-03-31 07:51 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +### 3. Tạo một kho chứa git
em không hiểu lỗi đâu a

2017-03-31 07:51 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +
dạ ok anh

2017-03-31 08:35 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +
Không đúng, kiểm tra lại cho anh xem working directory nó chứa cái gì. Viết thế này chưa chính xác.

2017-03-31 08:37 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Tuan_2.Git_Basic.md
> +### 3. Tạo một kho chứa git
Chỗ này anh nhầm.