Chinh sua bao cao
cloudcomputinghust/openstack-manual pull request #23
Opened 2017-04-05 03:07 UTC by Monlight

2017-04-05 04:20 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> -### Protocal
Typo

2017-04-05 04:41 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> -### Protocal
fix rồi ạ

2017-04-05 07:02 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> -Chúng ta hiểu nôm na protocol là sự thống nhất về cách thức trao đổi thông tin giữa các máy.
Nôm na ?

2017-04-05 07:02 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> +Khi 2 máy khác nhau muốn giao tiếp với nhau thì chúng cần một protocol(giao thức). Có thể hiểu đơn giản protocol là sự thống nhất về cách thức trao đổi thông tin giữa các máy.
Typo

2017-04-05 07:02 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> -### Protocal
Anh đặt review nhầm chỗ, xem bên dưới. Chưa fix.

2017-04-05 07:05 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> +Khi 2 máy khác nhau muốn giao tiếp với nhau thì chúng cần một protocol(giao thức). Có thể hiểu đơn giản protocol là sự thống nhất về cách thức trao đổi thông tin giữa các máy.
anh ơi cho em xem lại, đây là bản cũ ạ

2017-04-05 07:11 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> +Khi 2 máy khác nhau muốn giao tiếp với nhau thì chúng cần một protocol(giao thức). Có thể hiểu đơn giản protocol là sự thống nhất về cách thức trao đổi thông tin giữa các máy.
Em vừa push lại lên rồi ạ,

2017-04-05 08:38 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> -### Protocal
Em fix lại rồi đây ạ!

2017-04-05 16:59 UTC, vanduc95 commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> ++ Địa chỉ Broadcast: là địa chỉ dùng để gửi thông điệp đến tất cả các máy trong mạng nội bộ, địa chỉ Broadcast có toàn bộ các bits phần Host IP bằng 1 và dại diện cho toàn bộ các thiết bị trong mạng
Host IP --> Host ID

2017-04-05 16:59 UTC, vanduc95 commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
>  + Các máy còn lại trong mạng sẽ so sánh IP của mình với IP đích,B biết được máy A cần tìm là nó, khi đó B sẽ tạo gói tin APR Replay (chứa MAC của B) rồi gửi lại cho A, đồng thời nhập MAC, IP của A và
**Có thể nói rõ hơn:** thông điệp ARP request được gửi trong một **broadcast frame** (gửi tới tất cả các host), trong khi thông điệp ARP replay được gửi trong một **standard frame**, chỉ gửi lại cho host đã gửi yêu cầu.

Ngoài ra còn một số chỗ viết sai chính tả thôi, em vào sửa lại.

2017-04-06 09:18 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> ++ Địa chỉ Broadcast: là địa chỉ dùng để gửi thông điệp đến tất cả các máy trong mạng nội bộ, địa chỉ Broadcast có toàn bộ các bits phần Host IP bằng 1 và dại diện cho toàn bộ các thiết bị trong mạng
vâng ạ

2017-04-09 14:22 UTC, haminhcong commented
@vanduc95 Vào review cho Sang hộ tớ với.

2017-04-09 14:52 UTC, vanduc95 commented
@Monlight Mai anh review nhé, để anh đọc lại lí thuyết vài chỗ với ôn thi cái đã :))

2017-04-09 14:53 UTC, Monlight commented
vâng ạ

2017-04-09 21:52 GMT+07:00 Nguyễn Văn Đức <notifications@github.com>:

> @Monlight <https://github.com/Monlight> Mai anh review nhé, để anh đọc
> lại lí thuyết vài chỗ với ôn thi cái đã :))
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HPCC-Cloud-Computing/hpcc-know-how/pull/23#issuecomment-292790649>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARlivtE0-zuQNoBPLtayV19V_vDVnl_6ks5ruPDDgaJpZM4MzsYT>
> .
>

2017-04-11 19:10 UTC, vanduc95 commented
@Monlight: Bài viết của em mới nêu được khái niệm cơ bản về VLAN, cần bổ sung thêm các thứ sau:
+ Nói rõ cấu trúc của frame 802.1 Q, em mới đưa ra hình, cần giải thích.
+ Có những cách nào để kết nối 2 VLAN khác nhau trên cùng 1 switch và ở 2 switch khác nhau, từ đó mới nêu ra các khái niệm Trunk link, accsess link và quá trình chuyển frame như thế nào?

Tham khảo mục 5.4.4 [ở đây](https://drive.google.com/open?id=0B65JOd95W1-xNXVNUDEtWVQ2akU)

2017-04-12 02:12 UTC, hieulq requested changes
@Monlight sửa lại theo yêu cầu của anh Đức nhé

2017-04-27 16:15 UTC, Monlight commented
Các anh @haminhcong , @vanduc95 , @huynhducbk95 , @HaManhDong  review hộ em ạ.Em vừa hoàn thiện lại phần VXLAN, và Lệnh Linux.

2017-04-27 16:59 UTC, vanduc95 reviewed
Em mới chỉ tìm hiểu được các lệnh về file và thư mục, nên tìm hiểu thêm các lệnh căn bản về quản lí người dùng, mạng... Ngoài ra học sử dụng thành thạo một editor như nano, vi, vim.

2017-04-27 16:59 UTC, vanduc95 commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +Thực hành các lệnh trên Terminal. Trước tiên để mở Terminal bạn vào "Search your computer" gõ "Terminal" và nhấn chuột vào biểu tượng của Terminal để mở nó. Tiếp theo bạn có thể thực hành một số câu
Thường thì anh dùng phím tắt: Ctrl + Alt + T

2017-04-27 16:59 UTC, vanduc95 commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> ++ Dùng để xóa thư mục rỗng, có thể xóa đệ quy các thư mục nếu chúng đều rỗng
Nếu thư mục không rỗng thì dùng comand nào?

2017-04-27 18:06 UTC, Monlight commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> ++ Dùng để xóa thư mục rỗng, có thể xóa đệ quy các thư mục nếu chúng đều rỗng
rm -r <name directory> ạ

2017-04-27 18:14 UTC, Monlight commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +Thực hành các lệnh trên Terminal. Trước tiên để mở Terminal bạn vào "Search your computer" gõ "Terminal" và nhấn chuột vào biểu tượng của Terminal để mở nó. Tiếp theo bạn có thể thực hành một số câu
Vâng, bây giờ em mới biết phím tắt này, cảm ơn anh ạ.

Các lệnh về quản trị người dùng: chmod, chown,chgrp,useradd.... 
các lệnh về quản lí tiến trình: ps, kill, nice, renice, top, pgrep, at,crontab,...
một số lệnh khác như find, tee, grep, split, tr,ln, cut, diff, sort.
em đều biết ạ, nhưng thiếu thời gian viết tài liệu nên em sẽ cố gắng hoàn thiện trước chủ nhật tuần này ạ

2017-04-27 18:16 UTC, Monlight commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +Thực hành các lệnh trên Terminal. Trước tiên để mở Terminal bạn vào "Search your computer" gõ "Terminal" và nhấn chuột vào biểu tượng của Terminal để mở nó. Tiếp theo bạn có thể thực hành một số câu
Còn editor em biết dùng vi, vim, gedit rồi ạ, nhưng chủ yếu em viết và thực thi chương trình bằng vim ạ, em sẽ cố gắng tìm hiểu về nano. Cảm ơn anh ạ

2017-04-27 18:20 UTC, Monlight commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +Thực hành các lệnh trên Terminal. Trước tiên để mở Terminal bạn vào "Search your computer" gõ "Terminal" và nhấn chuột vào biểu tượng của Terminal để mở nó. Tiếp theo bạn có thể thực hành một số câu
Về mạng thì em mới biết câu lệnh thôi ạ, để em thử thực hành ạ

2017-04-27 18:22 UTC, vanduc95 commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +Thực hành các lệnh trên Terminal. Trước tiên để mở Terminal bạn vào "Search your computer" gõ "Terminal" và nhấn chuột vào biểu tượng của Terminal để mở nó. Tiếp theo bạn có thể thực hành một số câu
Không nhất thiết phải viết hết đâu, em thấy command nào quan trọng thì note lại thôi, một số command về cấu hình mạng với tìm kiếm file như **grep** em nên biết, sau này cài OpenStack sẽ dễ hơn. 

Nếu quen dùng vim rồi thì dùng luôn thôi, ko cần phải chuyển qua nano nữa đâu.

2017-04-27 19:09 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> ++ Khi chưa có VLAN: Thiết bị giới hạn miền quảng bá thường là các Router (do cơ chế chặn các bản tin quảng bá). Và cũng chính Router tạo ra các miền quảng bá bằng việc mỗi một giao diện của Router là
"Trong một broadcast domain, khi một máy tính gửi một frame thì frame đó sẽ được gửi tới tất cả các máy khác trong cùng miền này. "

Thật không ?

2017-04-27 19:12 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
"Khi áp dụng VLAN: Mỗi một VLAN là một miền broadcast. Một switch không hỗ trợ VLAN thì toàn bộ các máy tính, thiết bị cắm vào switch đó nằm trong một miền broadcast."

Câu này lủng củng, không rõ ý. Em đang giới thiệu về cái vấn đề "khi áp dụng VLAN" lại nhảy bụp một phát sang "một switch không hỗ trợ VLAN". Nếu không trình bày rõ ràng và dễ hiểu được bằng lời nói thì em vẽ hình minh họa ra cho anh.

2017-04-27 19:26 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
"Như vậy nếu không sử dụng kĩ thuật VLAN, mà muốn cho các thiết bị trong cùng 1 phòng ban có thể trao đổi dữ liệu nội bộ với nhau ta cần 9 switch (3 switch cho mỗi tầng) và số miền quảng bá tương ứng sẽ là 9 miền"

Có thật không ? Phải dùng tới 9 con switch cơ à ? Em vẽ ra cho anh xem xem là dùng 9 con đấy kiểu gì để chúng nó trao đổi dữ liệu nội bộ với nhau xem nào ?

"Mặt khác như hình trên, khi áp dụng VLAN ta thu được chỉ còn 3 miền broadcast mà các máy thuộc 3 tầng ở cùng một phòng ban vẫn có thể trao đổi dữ liệu với nhau."

Em giải thích hình vẽ kia cho anh được không ? . Vẽ một hình chi tiết đánh số các cổng, gán IP cho từng máy trong toàn bộ hệ thống (em tự chọn), giải thích **chi tiết** cho anh quá trình một gói tin nó đi từ một  máy ở Engineering VLAN sang Marketing VLAN như thế nào ?

2017-04-27 20:01 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +![access port](imageNet/vlan03.png)
Trên hình vẽ này của em thì chỗ nào là Access port ? Trong 2 con switch thì con nào không hỗ trợ VLAN, hay cả 2 con đều hỗ trợ VLAN ?

2017-04-27 20:01 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> ++ VLAN ID
VLAN Type: là tùy chọn cho việc triển khai VXLAN, mặc định là 0x8100 theo chuẩn 802.1Q Tagged Prototocol Identifier (TPUD) 

Cho anh xin nguồn của cái dòng này.

2017-04-27 20:01 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
1. Nếu MAC nguồn và MAC đích đến đều nằm cùng 1 Server lưu trữ thì gói tin được chuyển tới Switch (có cài đặt VTEP), được switch chuyển đến máy đích luôn và không có VXLAN encapsulation/de-encapsulation được thực hiện
+2. Nếu MAC đích không hoạt động cùng Server chứa host gửi gói tin, thì gói tin được đóng thành gói VXLAN bởi VTEP nguồn và được gửi tới VTEP tiếp theo dựa trên local table của nó. Tới VTEP có kết nối với host đích gói tin sẽ được loại bỏ các phần tiêu đề ngoài, và gói tin gốc sẽ được gửi tới host đích
+3. Với các gói tin Unicast không rõ, hoặc multicast. VTEP sẽ đóng gói thành gói VXLAN multicast rồi gửi đến các VTEP khác thuộc cùng nhóm multicast của 1 VXLAN segment (lúc này Outer Dest IP là IP của nhóm multicast)

Cho anh xin nguồn của cái đống này.

2017-04-27 20:01 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> + MAC-A | MAC-B | IP-A | IP-B | 80 | 100 | Data
Frame là ở tầng mấy ? Sao lại có IP với Port trong Frame là thế nào ?

2017-04-27 20:01 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Lấy một ví dụ khác cho anh, không sử dụng hình kia nữa, anh đã nói là nếu gọi anh vào review thì khi lấy ví dụ các em phải tự vẽ hình rồi mà. Vẽ hình khác đi.

2017-04-27 20:04 UTC, haminhcong commented
Anh nhắc lại là viết xong tài liệu, các em phải tự đọc lại tài liệu mình viết ít nhất 2 lần. Rất nhiều chỗ em vẫn bê nguyên từ câu tiếng Anh sang tiếng Việt mà không chịu đọc lại xem nó có lủng củng không đấy.

2017-04-28 03:42 UTC, hieulq commented
@haminhcong @vanduc95 good works! :+1:

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
> ++ Là giao thức truyền tin nhanh: truyền dữ liệu theo phương thức "best effort"
Truyền dữ liệu theo phương thức "best effort" nghĩa là sao? giải thích cụ thể cho anh câu này?

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/basic_computer_network01.md
cho ví dụ thì giải thích ví dụ với chứ ?

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Phần này là nguyên nhân ra đời đúng hơn là lịch sử ra đời

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
giao diện của Router là cái gì?

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
"các thiết bị trong cùng 1 phòng ban có thể trao đổi dữ liệu nội bộ với nhau"
trong ví dụ này thì các máy tính trong một phòng ban (vd: Engineering) ở các tầng khác nhau thì có trao đổi dữ liệu nội bộ cho nhau được không?

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
"Mỗi phủ được gọi là 1 VXLAN segment" mỗi phủ là gì vậy?
từ nào không dịch được thì cứ để tiếng anh, rồi giải thích là được mà :))

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Như trong Hình 2.4 Cơ chế khám phá và học địa chỉ trong VXLAN
anh thấy tại bước gói tín đến VTEP-1 đóng gói VXLAN packet có địa chỉ MAC des: 00:01:SE:01:01:01 thì MAC address này là của thằng nào? em nên giải thích rõ hơn đoạn này

2017-04-28 06:28 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +    + `-r`: dùng để xóa thư mục
đây mới là những lệnh cơ bản trong linux, ngoài ra em nên tìm hiểu về user, group và các quyền trong linux, cách thêm, sửa, xóa quyền đối với một file để hoàn thiện hơn tài liệu. :))

2017-04-28 07:20 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Hỏi câu này nghĩa là sao ? Bối cảnh của câu hỏi này là trước khi triển khai VLAN hay sau khi triển khai VLAN ???

2017-04-28 07:29 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Router Interface. Các port trên con router.

2017-04-28 07:29 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Không nhận xét kiểu vặn vẹo.

2017-04-28 07:32 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Cái này tớ nhắc mãi nó rồi, không chịu sửa. Bảo viết xong phải đọc lại bài viết mà không bao giờ nghe. Như kiểu mấy đứa nó dùng Google Translate để viết báo cáo ấy.

2017-04-28 07:50 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Lịch sử ra đời là quá trình phát triển đi từ các phiên bản đầu tiên, theo các thời gian phát triển của một vấn đề nào đó. Còn đây, nếu nội dung của lịch sử chỉ có thế này thì đây là nguyên nhân thì đúng hơn.
Đây chỉ là góp ý dùng từ thôi mà, vặn vẹo gì đâu @@

2017-04-28 07:51 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
câu này tớ đang hỏi em nó mà -_-

2017-04-28 07:55 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Sao phải hỏi ? Chỗ này em nó có viết sai đâu, hỏi làm gì ?

2017-04-28 07:57 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Chỗ này em nó viết không có vấn đề gì cả. Thông tin em nó đưa ra là chính xác, không có vấn đề.

2017-04-28 07:58 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
chỗ này không sai, ý tớ là đang nói đến cách dùng từ "giao diện của Router", để xem giao diện của Router là cái gì

2017-04-28 08:07 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Em nó chuyển router interface thành giao diện của router là đúng. Mặc dù dùng router interface thì rõ ràng hơn, tuy nhiên không có vấn đề gì. 

"Khi chưa có VLAN: Thiết bị giới hạn miền quảng bá thường là các Router (do cơ chế chặn các bản tin quảng bá). Và cũng chính Router tạo ra các miền quảng bá bằng việc mỗi một giao diện của Router là một Broadcast domain."

Câu này em nó viết như thế này là đúng và chính xác rồi.

2017-04-28 08:09 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Thông tin đưa ra là chính xác, tớ đang góp ý về tiêu đề cho hợp lý

2017-04-28 08:15 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
ừ, phần này tớ đặt nhầm review, tớ chỉ hỏi về router interface thôi

2017-04-28 08:48 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
ý của câu hỏi này là trong trường hợp không có VLAN, đơn thuần dùng 9 switch không hỗ trợ VLAN như em nó bảo. Thì các phòng ban có thực sự trao đổi dữ liệu được cho nhau hay không? nó trao đổi kiểu gì? chỗ này chưa rõ ràng lắm.

2017-04-28 13:38 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Thế cậu có thấy trên kia tớ hỏi nó câu này rồi không?

2017-04-28 14:13 UTC, huynhducbk95 commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
những câu này tớ soạn từ tối hôm qua, nhưng quên mất không submit request. Nên trưa nay submit lại luôn. Đừng spam nữa @@

2017-04-28 14:20 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Ơ hay. Làm việc với nhau thì phải rõ ràng chứ.  Tớ spam cái gì?

2017-04-29 09:15 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
vâng ạ

2017-04-29 09:19 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> + MAC-A | MAC-B | IP-A | IP-B | 80 | 100 | Data
theo em tìm hiểu thì frame là tên gọi của gói tin sau khi dữ liệu từ tầng ứng dụng đi xuống và được đóng gói qua từng tầng dưới, ví dụ tại tầng Network thì gói tin đóng gói được gọi là IP packet. frame em viết ở đây không phải là khung Ethernet ạ.

2017-04-29 09:22 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Tài liệu : https://www.arista.com/assets/data/pdf/Whitepapers/Arista_Networks_VXLAN_White_Paper.pdf

Trang 3, mục VXLAN frame encapsulation and forwarding

2017-04-29 09:24 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +![access port](imageNet/vlan03.png)
em tham khảo ở tài liệu này ạ
https://www.arista.com/assets/data/pdf/Whitepapers/Arista_Networks_VXLAN_White_Paper.pdf

2017-04-29 09:28 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +![access port](imageNet/vlan03.png)
Em lấy hình vẽ để minh họa thì em phải làm sao cho người đọc thấy cái Accessport của em nó nằm chỗ nào. Vấn đề  không phải là em tham khảo ở đâu, mà là hình vẽ của em nó thiếu ký hiệu, thiếu chi tiết nên người đọc - là anh không hiểu được.

2017-04-29 09:28 UTC, Monlight commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Em sẽ viết lại. Tách câu trên thành 2 ý, để ý "Một switch ... broadcast." lên trước. Ý "Khi áp dụng VXLAN ...broadcast" để xuống sau ạ.

2017-04-29 09:30 UTC, Monlight commented on K59/Nguyen-Van-Sang/linux/basic_linux.md
> +Thực hành các lệnh trên Terminal. Trước tiên để mở Terminal bạn vào "Search your computer" gõ "Terminal" và nhấn chuột vào biểu tượng của Terminal để mở nó. Tiếp theo bạn có thể thực hành một số câu
vâng ạ

2017-04-29 09:35 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> + MAC-A | MAC-B | IP-A | IP-B | 80 | 100 | Data
"theo em tìm hiểu thì frame là tên gọi của gói tin sau khi dữ liệu từ tầng ứng dụng đi xuống và được đóng gói qua từng tầng dưới" 
"frame em viết ở đây không phải là khung Ethernet ạ."
Cái gì thế này ?
Cái gì thế này ?

2017-04-29 09:45 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Đây là tài liệu nói về VXLAN trong môi trường ảo hóa. Không phải là tài liệu nói về VXLAN tổng quát. 

Mà em đọc tài liệu thì em phải đọc xem cái tài liệu cuả em nó nói về cái gì, nó trình bày hệ thống trong môi trường như thế nào ? Em có hiểu người ta viết cái gì không mà em dám dịch từ "host" thành từ Server lưu trữ ? Lưu trữ cái gì ? dữ liệu à ?

Lại còn cái dòng này nữa "Nếu MAC đích không hoạt động cùng Server chứa host gửi gói tin"

Server chứa host????? Host là cái gì? Server là cái gì? Em có biết nghĩa của 2 khái niệm này không mà dám dịch thế này?
Em có đọc lại bài viết của mình không đấy ?

Nội dung em viết ra không chính xác.

2017-04-29 09:48 UTC, haminhcong commented on K59/Nguyen-Van-Sang/computer_network/VLAN, VXLAN.md
> +
Cho anh xin tài liệu chỗ này.

2017-04-29 09:50 UTC, haminhcong commented
@Monlight Reply lại tất cả các comment em chưa reply cho anh.

2017-08-31 16:53 UTC, daikk115 commented on K59/Nguyen-Van-Sang/git/basic_git.md
Anh share chút outdated slide hi vọng còn hữu ích :D Chỉ muốn nhận mạnh lại sự khác nhau giữa git, github, gitlab (EE, CE) và thêm một số thằng như merge, cherry-pick, revert, rebase, .... hay đơn giản là fix merge conflict - cực kỳ hữu ích trong thực tế.
http://slides.com/daikk115/deck-04a47616-4641-4184-b926-e1eac8dde966/live#/

2017-09-01 02:30 UTC, NTT-TNN commented on K59/Nguyen-Van-Sang/git/basic_git.md
Dạ. Hay quá anh ạ.

2017-09-01 15:43 UTC, closed without merging