Initialize  Consistency model document
cloudcomputinghust/openstack-manual pull request #27
Opened 2017-04-08 08:26 UTC by haminhcong

2017-04-12 02:25 UTC, hieulq requested changes

2017-04-12 02:25 UTC, hieulq commented on DistributedSystem/Data-Consistency-Model.md
> +Một trong những thành phần chính tạo ra một hệ thống thông tin, đó là các đối tượng dữ liệu. Các đối tượng dữ liệu trên hệ thống thông tin có thể tồn tại dưới những dạng khác nhau, như các cơ sở dữ l
hệ thống đơn tiến trình? Nếu so sánh thì so hệ phân tán với hệ tập trung, không ai so kiểu thế này cả

2017-04-12 02:25 UTC, hieulq commented on DistributedSystem/Data-Consistency-Model.md
> +Chúng ta có thể thấy cơ chế sao lưu (data replication) cung cấp rất nhiều lợi ích cho hệ thống phân tán. Tuy nhiên,đi cùng với các lợi ích mang lại, việc một đối tượng dữ liệu có nhiều bản sao trong
How about nhược điểm khác ngoài việc truy xuất này? Khen mà không có chê à?

2017-04-12 02:25 UTC, hieulq commented on DistributedSystem/Data-Consistency-Model.md
> +Ví dụ, trong hệ thống phân tán có thể xảy ra sự kiện cùng 1 lúc nhiều client yêu cầu thay đổi nội dung của một replica:
Có lẽ nên nói về CAP Theorem ở ngay phần đầu này.

2017-04-12 02:28 UTC, haminhcong commented on DistributedSystem/Data-Consistency-Model.md
> +Một trong những thành phần chính tạo ra một hệ thống thông tin, đó là các đối tượng dữ liệu. Các đối tượng dữ liệu trên hệ thống thông tin có thể tồn tại dưới những dạng khác nhau, như các cơ sở dữ l
Em so sánh hệ phân tán với hệ tập trung, để chỉ ra là hệ phân tán khác với hệ tập trung ở chỗ là một đối tượng dữ liệu trong hệ phân tán có nhiều bản sao ạ. Thì từ cái vấn đề có nhiều bản sao thì mới đi đến cái chỗ mình sử dụng phương pháp nào để nội dung các bản sao nó giống nhau - đồng bộ hóa các bản sao ấy anh.

2017-04-12 02:28 UTC, haminhcong commented on DistributedSystem/Data-Consistency-Model.md
> +Ví dụ, trong hệ thống phân tán có thể xảy ra sự kiện cùng 1 lúc nhiều client yêu cầu thay đổi nội dung của một replica:
Vâng ạ.

2017-04-12 02:33 UTC, hieulq commented on DistributedSystem/Data-Consistency-Model.md
> +Một trong những thành phần chính tạo ra một hệ thống thông tin, đó là các đối tượng dữ liệu. Các đối tượng dữ liệu trên hệ thống thông tin có thể tồn tại dưới những dạng khác nhau, như các cơ sở dữ l
vậy cách dẫn dắt của em có nói tới hệ tập trung không? tại sao lại đập thẳng luôn là "hệ thống đơn tiến trình truyền thống".
một hệ tập trung hoàn toàn có thể đa tiến trình nhé

2017-04-12 02:51 UTC, haminhcong commented on DistributedSystem/Data-Consistency-Model.md
> +Một trong những thành phần chính tạo ra một hệ thống thông tin, đó là các đối tượng dữ liệu. Các đối tượng dữ liệu trên hệ thống thông tin có thể tồn tại dưới những dạng khác nhau, như các cơ sở dữ l
Vâng ạ. Em hiểu rồi anh ạ.
Vậy em sẽ thay hệ đơn tiến trình bằng hệ tập trung ạ.

2017-04-12 12:54 UTC, haminhcong commented on DistributedSystem/Data-Consistency-Model.md
> +Chúng ta có thể thấy cơ chế sao lưu (data replication) cung cấp rất nhiều lợi ích cho hệ thống phân tán. Tuy nhiên,đi cùng với các lợi ích mang lại, việc một đối tượng dữ liệu có nhiều bản sao trong
Vâng ạ, em sẽ suy nghĩ tiếp về các nhược điểm của hệ phân tán ạ.

2017-04-17 03:03 UTC, hieulq commented
@daikk115 @ntk148v vào đọc thêm để tăng know-how nhé. Công nó đi bài bản hơn 2 thằng đó.

2017-04-18 13:14 UTC, haminhcong commented on DistributedSystem/Data-Consistency-Model.md
> +Ví dụ, trong hệ thống phân tán có thể xảy ra sự kiện cùng 1 lúc nhiều client yêu cầu thay đổi nội dung của một replica:
Anh ơi, em nghĩ là mình nên trình bày cái định lý CAP sau khi đã giới thiệu về 2 mô hình ACID và BASE anh ạ. Vì trong này ông phát biểu định lý này cũng nói tới CAP sau 2 mô hình kia ạ.

http://pld.cs.luc.edu/courses/353/spr11/notes/brewer_keynote.pdf

Với cả trong giải thích của wikipedia, thì trong CAP, cái consistency nó là một tính chất cái cụ thể chứ không mang tính tổng quá nữa ạ:

Consistency: Every read receives the most recent write or an error

2017-04-18 14:02 UTC, hieulq commented
@haminhcong: CAP là theorem, tổng quát hơn ACID và BASE.
Nói một cách khác là độ liên quan có nhưng không nhiều, thêm nữa theorem thì nên đi trước một cái gì đó cụ thể.
Một ví dụ là consistency của CAP là tổng quát và khác biệt so với Consistency trong ACID.
@minhnb thầy vào validate với trò này, nó bẩu C trong CAP là cụ thể chứ không tổng quát.

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GCS/CM/IT/M/MU d-@? s+(++):+(++) !a C++++(++++)$ ULC++++(++)$ P L++(+++)$ E !W N* o+ K w O- M V- PS+ PE++ Y+ PGP+ t 5 X R tv+ b+(++)>+++ DI- D+ G e++(+++) h-- r(++)>+++ y-
------END GEEK CODE BLOCK------

On Apr 18, 2017, 20:15 +0700, haminhcong <notifications@github.com>, wrote:
>
> @haminhcong commented on this pull request.
>
>
> In DistributedSystem/Data-Consistency-Model.md (https://github.com/HPCC-Cloud-Computing/hpcc-know-how/pull/27#discussion_r111949488):
>
> > @@ -0,0 +1,33 @@ +# Data Consistency Model In Distributed System + + +Một trong những thành phần chính tạo ra một hệ thống thông tin, đó là các đối tượng dữ liệu. Các đối tượng dữ liệu trên hệ thống thông tin có thể tồn tại dưới những dạng khác nhau, như các cơ sở dữ liệu, các file hoặc thậm chí là các đối tượng nằm trong bộ nhớ RAM của một process. Tuy nhiên, cách thức sử dụng và quản lý các đối tượng dữ liệu trong một hệ thống phân tán có sự khác biệt với một hệ thống đơn tiến trình truyền thống. Khác với các hệ thống đơn tiến trình truyền thống thường chỉ lưu trữ và quản lý các đối tượng dữ liệu dưới dạng một thực thể duy nhất, trong một hệ thống phân tán, một đối tượng dữ liệu có thể tồn tại dưới dạng nhiều thực thể giống nhau - được gọi là các bản sao (replica) của đối tượng. + +Việc tạo ra nhiều bản sao cho một đối tượng dữ liệu có rất nhiều ưu điểm, ví dụ như cho phép tăng hiệu năng tổng thể của hệ thống, do việc trên hệ thống việc có nhiều bản sao cho phép cung cấp nhiều tài nguyên hơn. Đồng thời, việc có nhiều bản sao của một đối tượng dữ liệu trên hệ thống cho phép hệ thống có khả năng chống lỗi tốt hơn, do khi sự cố xảy ra trên một thành phần nào đó, thì các bản sao khác của các đối tượng dữ liệu vẫn tồn tại ở trên các thành phần khác trong hệ thống, do đó hệ thống vẫn có khả năng phục hồi lại dữ liệu cho người dùng. + +Chúng ta có thể thấy cơ chế sao lưu (data replication) cung cấp rất nhiều lợi ích cho hệ thống phân tán. Tuy nhiên,đi cùng với các lợi ích mang lại, việc một đối tượng dữ liệu có nhiều bản sao trong hệ thống phân tán cũng đặt ra cho chúng ta một số vấn đề cần giải quyết. Đó là trong hệ thống phân tán, khi nhiều bản sao đồng thời phục vụ cho nhiều thực thể (các tiến trình và cácclient) khác nhau và bị các thực thể này thay đổi nội dung, làm sao để chúng ta xác định được tại một thời điểm xác định, đối tượng dữ liệu cũng như các bản sao của nó trên hệ thống sẽ có giá trị là gì ? + +Ví dụ, trong hệ thống phân tán có thể xảy ra sự kiện cùng 1 lúc nhiều client yêu cầu thay đổi nội dung của một replica:
>
> Anh ơi, em nghĩ là mình nên trình bày cái định lý CAP sau khi đã giới thiệu về 2 mô hình ACID và BASE anh ạ. Vì trong này ông phát biểu định lý này cũng nói tới CAP sau 2 mô hình kia ạ.
>
>
> http://pld.cs.luc.edu/courses/353/spr11/notes/brewer_keynote.pdf
>
>
> Với cả trong giải thích của wikipedia, thì trong CAP, cái consistency nó là một tính chất cái cụ thể chứ không mang tính tổng quá nữa ạ:
>
>
> Consistency: Every read receives the most recent write or an error
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub (https://github.com/HPCC-Cloud-Computing/hpcc-know-how/pull/27#discussion_r111949488), or mute the thread (https://github.com/notifications/unsubscribe-auth/ABui7vuPa_kHssKyjjxfeYYFmLRY1N8kks5rxLdTgaJpZM4M3owY).
>
>
>

2017-04-19 04:55 UTC, haminhcong commented
Em vừa cấu trúc lại bài viết và thêm định lý CAP và mô hình BASE vào ạ. Anh review hộ em được không ạ ?

2017-04-19 10:59 UTC, haminhcong commented
À anh Hiếu ơi, cái CAP đúng là nó tổng quát hơn cái BASE ạ. Em bị lẫn lộn chỗ đó ạ :(

2017-04-28 03:44 UTC, hieulq commented
@haminhcong anh merge PR này, các request sửa khác đẩy ở PR khác.
Thế này tạm ổn rồi!

2017-04-28 03:44 UTC, hieulq approved these changes

2017-04-28 03:44 UTC, hieulq commented
@daikk115 và @ntk148v rảnh đọc lại lý thuyết qua PR này của Công nhé.

2017-04-28 03:44 UTC, merged