Git branch + git convention
cloudcomputinghust/openstack-manual pull request #28
Opened 2017-04-08 12:27 UTC by NTT-TNN

báo cáo về nhánh trong git và các để viết commit trong git.

2017-04-09 14:18 UTC, haminhcong commented
@huynhducbk95 vào review cho em nó hộ tớ với.

2017-04-12 02:18 UTC, hieulq requested changes

2017-04-12 02:18 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
> +### 3. Tạo một kho chứ git
kho chứ?

2017-04-12 02:18 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
> +Có hai cách để tạo một kho chứ git
typo

2017-04-12 02:18 UTC, hieulq commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part2.md
> +
vẫn chưa có phần rebase và cherry-pick, bổ sung ở part sau nhé

2017-04-12 02:22 UTC, NTT-TNN commented
Em bổ sung rebase rồi anh à

2017-04-12 02:25 UTC, hieulq approved these changes

2017-04-13 01:13 UTC, hieulq approved these changes

2017-04-13 01:14 UTC, merged