Update git_part1 + cac_mang_cuc_bo
cloudcomputinghust/openstack-manual pull request #29
Opened 2017-04-13 13:32 UTC by NTT-TNN

Update git la gi trong git+part
Viet ve cac mang cuc bo VLAN, GRE,VXLAN commit time 1.

2017-04-13 13:34 UTC, NTT-TNN commented
@hieulq @haminhcong @vanduc95 @huynhducbk95  Review em với các anh.

2017-04-14 11:35 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
>  - Các hệ thống VCS khác mỗi khi người sử dụng commit VCS sẽ lưu lại toàn bộ các file. Còn với Git hệ thống sẽ lưu lại một **ảnh chụp(snapshot)** các file. Với những file đã thay đổi git sẽ tạo một ph
Có một  cái ảnh lỗi em chưa sửa cho anh à ?

2017-04-14 11:35 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
>  - Các hệ thống VCS khác mỗi khi người sử dụng commit VCS sẽ lưu lại toàn bộ các file. Còn với Git hệ thống sẽ lưu lại một **ảnh chụp(snapshot)** các file. Với những file đã thay đổi git sẽ tạo một ph
"Các hệ thống VCS khác mỗi khi người sử dụng commit VCS sẽ lưu lại toàn bộ các file."

Anh nhớ là đoạn này anh đã nhắc em sửa ít nhất 1 lần rồi

2017-04-14 11:35 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
> +Git là một VCS, cụ thể hơn là một DVCS sau đây ta sẽ đi vậy git khác với các VCS khác như thế nào, tại sao ta nên sử dụng git cũng như cách sử dụng git cơ bản.
"Git là một VCS, cụ thể hơn là một DVCS sau đây ta sẽ đi vậy git khác với các VCS khác như thế nào"

Em định nói cái gì đây ?

2017-04-14 11:49 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Máy A tạo một Ethernet frame với địa chỉ nguồn là IP và MAC của A và địa chỉ đích là IP và MAC của B sau đó gửi tới VTEP-1.
L2 Frame không bao giờ chứa địa chỉ nguồn là IP. Đọc lại phần này

2017-04-14 11:49 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Máy A tạo một Ethernet frame với địa chỉ nguồn là IP và MAC của A và địa chỉ đích là IP và MAC của B sau đó gửi tới VTEP-1.
Vẽ hình, lấy ví dụ như cách mà 2 tuần trước em hướng dẫn em.

2017-04-14 11:49 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +
Lấy lại ví dụ cho anh. Anh muốn thấy khi dữ liệu đi qua các đối tượng trong hệ thống thì nó được đóng gói vào gói tin gì, khi nó đến các trạm cuối thì dữ liệu được bóc tách ra như thế nào. Viết từng bước 1 ra cho anh, sau mỗi bước dữ liệu có hình dạng như thế nào, bao gồm các trường gì, mỗi trường có giá trị là gì, em vẽ ra cho anh.

2017-04-14 11:49 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
>  Mạng flat là một mạng không cung cấp bất kỳ một tùy chọn thêm nào. Nó là mạng truyền thống được sử dụng ở Layer2. Mạng flat phân tách miền quảng bá bằng cách sử dụng router và mội máy kết nối đến cùn
"Mạng flat phân tách miền quảng bá bằng cách sử dụng router"

Xem lại câu này. Không đúng, vì nó mâu thuẫn với câu dưới:

 Nói chung là tất cả các thiết bị trong một mạng flat có cùng một miền quảng bá.

2017-04-14 15:27 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
>  - Các hệ thống VCS khác mỗi khi người sử dụng commit VCS sẽ lưu lại toàn bộ các file. Còn với Git hệ thống sẽ lưu lại một **ảnh chụp(snapshot)** các file. Với những file đã thay đổi git sẽ tạo một ph
@haminhcong  ảnh nào lỗi anh ơi?

2017-04-14 15:29 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Máy A tạo một Ethernet frame với địa chỉ nguồn là IP và MAC của A và địa chỉ đích là IP và MAC của B sau đó gửi tới VTEP-1.
Em sẽ sửa sau anh à tối nay e bận làm bài tập lớn rồi anh @haminhcong

2017-04-14 16:44 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Git_tutorial/Git_Basic_Part1.md
>  - Các hệ thống VCS khác mỗi khi người sử dụng commit VCS sẽ lưu lại toàn bộ các file. Còn với Git hệ thống sẽ lưu lại một **ảnh chụp(snapshot)** các file. Với những file đã thay đổi git sẽ tạo một ph
https://raw.githubusercontent.com/NTT-TNN/Basic_knowledge/master/images/File%20Status%20LifeCycle.PNG

2017-04-17 03:00 UTC, hieulq requested changes
Fix lại theo yêu cầu của Công.

2017-04-20 04:20 UTC, haminhcong commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +VTEP là một thiết bị được VXLAN sử dụng để encapsulation and de-encapsulation các gói tin vận chuyển và ánh xạ các máy trong VXLAN. VTEP cung cấp hai interface một là switch interface trong mạng LAN
VTEP bao gồm những thành phần nào ? Và làm những nhiệm vụ nào ?

2017-04-20 04:21 UTC, haminhcong commented
@huynhducbk95 @vanduc95 @HaManhDong vào review cho Thạo giúp mình với.

2017-04-20 04:22 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +VTEP là một thiết bị được VXLAN sử dụng để encapsulation and de-encapsulation các gói tin vận chuyển và ánh xạ các máy trong VXLAN. VTEP cung cấp hai interface một là switch interface trong mạng LAN
em sẽ bổ sung ạ

2017-04-20 06:46 UTC, vanduc95 commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Bảng địa chỉ MAC của switch quá lớn.
Tại sao bảng địa chỉ MAC của switch lại quá lớn, nó khác gì bảng địa chỉ MAC khi không sử dụng VLAN?

2017-04-20 06:50 UTC, vanduc95 commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
>  Giải pháp đó có một vấn đề nếu một switch có nhiều mạng VLAN kết nối sẽ tốn nhiều cổng cho và sẽ không hiệu quả. Một giải pháp khác là sử dụng một cổng đặc biệt trên mỗi switch gọi là trunk port để k
Phần này anh bổ sung thêm cách thứ 3 là nối 2 con switch với cùng một router.

2017-04-20 07:54 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Bảng địa chỉ MAC của switch quá lớn.
khác chứ anh. Khi không sử dụng VLAN (tức là không có mạng LAN ảo) thì switch sẽ chỉ cần lưu một số IP ứng với địa chỉ MAC nếu tím trong bảng đó không có thì sẻ gửi ARP request để tìm địa chỉ MAC đó còn với VLAN thì buộc phải lưu tất cả địa chỉ MAC để biết nó thuộc VLAN ID nào ạ.

2017-04-20 07:55 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
>  Giải pháp đó có một vấn đề nếu một switch có nhiều mạng VLAN kết nối sẽ tốn nhiều cổng cho và sẽ không hiệu quả. Một giải pháp khác là sử dụng một cổng đặc biệt trên mỗi switch gọi là trunk port để k
em viết thiếu ạ. Trunk port cũng dùng để nốt với router em sẽ bổ sung ạ

2017-04-20 08:26 UTC, vanduc95 commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Bảng địa chỉ MAC của switch quá lớn.
Anh nghĩ em đang nhầm giữa `mac table` và `arp table` . Khi có hay không có VLAN thì `mac table' vẫn có một cấu trúc như vậy
-------------------------------------------
Vlan    Mac Address       Type        Ports
----    -----------       --------    -----
   1    00ld.70ab.5d60    DYNAMIC     Fa0/2
   1    00le.f724.al60    DYNAMIC     Fa0/3

Mặc định khi không cấu hình VLAN thì tất cả các port trên switch đều thuộc VLAN 1, khi cấu hình VLAN thì nó chỉ thay trường **vlan** bằng VLANID của port đó. Vậy nên bảo "Bảng địa chỉ MAC của switch quá lớn" thì anh thấy hơi sai sai.
Kiểm tra lại nhé :))

2017-04-20 08:28 UTC, NTT-TNN commented on K59/Nguyen-Tien-Thao/Mang_May_Tinh/Tuan_2.Cac_mo_hinh_mang_cuc_bo.md
> +- Bảng địa chỉ MAC của switch quá lớn.
dạ vâng em sẽ check lại

2017-04-20 09:23 UTC, NTT-TNN commented
@haminhcong @vanduc95 @huynhducbk95 @HaManhDong  review cho em với. Về phần linux em không biết có cần thêm gì không ạ?

2017-05-05 01:08 UTC, hieulq approved these changes
Anh approve PR này.
Review qua:
- Các khái niệm thì các em đã nắm được sơ lược, nhưng cách trình bày chưa thoáng lắm. Hiện tại cứ merge và 1 năm sau đọc lại xem thế nào nhé. ;)
- @haminhcong @huynhducbk95 @vanduc95 nên cho các em thực hành thêm để hiểu, đừng lý thuyết thuần quá.

2017-05-05 01:08 UTC, merged

2017-05-05 02:21 UTC, NTT-TNN commented
@hieulq  dạ vâng anh. Em cũng đang thử cài máy ảo và config mạng như anh @haminhcong giao trên trello nhưng em đang bị lỗi ở phần cài máy ảo bằng KVM ạ :)

2022-11-06 00:20 UTC, Zalotuan0934346524 commented on K59/Nguyen-Tien-Thao/Linux/Linux_tutorial.md
> +build    distributted  official_bktranslator  Public           Videos
- - - [x] ![Uploading 200148264...]