Tim hieu ve Git + Linux
cloudcomputinghust/openstack-manual pull request #32
Opened 2017-08-26 08:33 UTC by nghiadt16

Tim hieu ve Git + Linux

2017-08-28 04:40 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +- **Vì sao nên dùng VCS**:
Hôm sau em lên anh dạy em dùng visual studio code để viết báo cáo mark down nhé. Em viết bằng cái kia lỗi hết format rồi này https://github.com/nghiadt16/hpcc-know-how/blob/813ce7a968ee0c31349e671c21a6ca3aeae1b02d/K59/Duong-Trung-Nghia/Git/basic.md

2017-08-28 14:51 UTC, haminhcong requested changes

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +    * Mỗi lần bạn "commit", hoặc lưu lại trạng thái hiện tại của dự án trong Git, về cơ bản Git "chụp một bức ảnh" ghi lại nội dung của tất cả các tập tin tại thời điểm đó và tạo ra một tham chiếu tớ
Lần sau up ảnh chứ không chèn link vào em nhé.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +   ![Hình minh hoạ](https://git-scm.com/figures/18333fig0106-tn.png)
Đây là 3 trạng thái của một tệp tin đang ở working directory của git trong một git project và đã được git quản lý chứ không phải là trạng thái của git. Em sử dụng từ git ở đây chưa chính xác lắm.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +
cái thứ 3 viết chưa rõ ràng lắm. Em có thể viết kiểu như "Tạo commit để lưu lại các snapshot của các tệp tin trong Stagging area." thì sẽ rõ ràng hơn.

1 Vấn đề nữa, là đây chỉ là một flow rất cơ bản khi làm việc với Git. Trong thực tế làm việc với Git nó sẽ có thêm một số các thao tác khác cũng như một số trạng thái khác của các file nhé.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +        git status
em liệt kê cho anh các trạng thái có thể có của một file được không  ?

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +        git commit -m [message]
em nói cho anh sau khi thực hiện lệnh git commit thì trong project xảy ra những thay đổi gì được không ?

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +
hôm sau lên gặp anh lấy ví dụ cho anh về các lệnh này em nhé.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +- Git không lưu trữ dữ liệu dưới dạng một chuỗi các thay đổi hoặc delta, mà thay vào đó là một chuỗi các ảnh (snapshot)
Chỗ này em nên đặt tên là Commit và Branch trong Git. Vì anh thấy nội dung em viết có gần 1 nửa là giới thiệu kỹ về commit và cách Git tổ chức một commit trong Git rồi.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +
Commit trong git có một tính chất đặc biệt, đó là một commit luôn luôn trỏ tới một commit phía trước (tất nhiên trừ commit đầu tiên của project). Chính nhờ tính chất này mà chúng ta mới thực hiện được việc phân nhánh và gộp nhánh. Em tìm hiểu về vấn đề này rồi hôm sau trình bày và lấy ví dụ cho anh nhé.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +        git pull <branch> (kéo về và tích hợp)
Hôm sau giải thích - lấy ví dụ cho anh git pull và git merge thực hiện công việc gì nhé.

2017-08-28 14:51 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Linux/basic.md
> +
Phần linux thì nó còn liên quan tới kiến thức về hệ điều hành, còn các câu lệnh cơ bản như thế này là được rồi.

Phần thực hành sử dụng linux anh sẽ để em thực hành trực tiếp trên máy vật lý của trung tâm nhé.

2017-09-01 04:26 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +    ![Hình minh hoạ](images/img_2.png)
1. 5 Loại đối tượng chứ không phải là 5 đối tượng.
1. Em bảo là 5 nhưng em mới đưa ra cho anh có 3 cái.
1. Cái ảnh minh họa với cái câu này của em nó không ăn nhập với nhau lắm. Anh đang hiểu là cái ảnh nó đang thể hiện Cấu trúc của một cái commit object, chứ không phải là thể hiện cấu trúc của một repository.

Check và sửa lại chỗ này cho anh. Anh chưa hiểu rõ lắm ý tưởng chỗ này em định nói tới cấu trúc của một **git repository** hay là cấu trúc của một **commit object**, vì cái ảnh với cái nội dung mâu thuẫn với nhau.

2017-09-01 04:26 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +* Một nhánh trong Git đơn thuần là một con trỏ có khả năng di chuyển được, trỏ đến một trong những commit này. Tên nhánh mặc định của Git là master. Như trong những lần commit đầu tiên, chúng đều đượ
Và mỗi lần bạn thực hiện commit, nó sẽ được tự động ghi vào theo hướng tiến lên.

Viết rõ ràng lại chỗ này cho anh. Em nói "nó sẽ được tự động ghi vào theo hướng tiến lên" nhưng là tiến lên theo hướng nào ? Nếu anh coi mỗi một branch là một hướng thì trong git repository của anh có rất nhiều hướng. Nhưng commit sẽ chỉ đi lên theo một hướng thôi. Em viết làm sao để anh hiểu được commit nó tiến lên theo hướng nào trong các hướng của repo.

2017-09-01 04:32 UTC, haminhcong commented
@nghiadt16 Xem lại cho anh về 2 chỗ kia.

Còn về cái việc mà hôm trước em bảo là một snapshot của một commit chỉ lưu lại các thay đổi của commit đó so với commit trước thì anh hôm nay đã check lại, cái này không đúng. một snapshot của một commit - chính là cái tree gốc mà em nói tới trong bài viết nó lưu lại toàn bộ các file trong project tại thời điểm commit, chứ không chỉ những file bị thay đổi.

Tối nay nếu anh có thời gian anh sẽ viết cho em một ví dụ. Không thì em đọc ở bài viết này rồi check lại cho anh vấn đề này:

[http://shafiulazam.com/gitbook/1_the_git_object_model.html](http://shafiulazam.com/gitbook/1_the_git_object_model.html)

Em dùng lệnh `git show -s --pretty=raw <commit_id>` để kiểm tra nội dung của một commit, và lấy ra cái tree_id của cái tree gốc của commit, sau đó dùng lệnh ` git cat-file -p <tree_id>` để xem nội dung của tree gốc.

Check lại vấn đề này cho anh.

2017-09-01 04:34 UTC, haminhcong commented
Bài viết khá tốt, sửa nốt 2 chỗ kia cho anh rồi anh bảo anh Hiếu merge request này cho em.

2017-09-01 09:14 UTC, nghiadt16 commented on K59/Duong-Trung-Nghia/Git/basic.md
> +    ![Hình minh hoạ](images/img_2.png)
3 loại đối tượng là: Blob, Tree và Commit. Commit sẽ trỏ đến Tree và Tree sẽ trỏ đến Blob
Còn 5 đối tượng là: 3 Blob, 1 Tree và 1 Commit  mà anh.
Chỗ này là em đang nói tới cấu trúc của 1 Commit object ạ

2017-09-01 09:15 UTC, nghiadt16 commented on K59/Duong-Trung-Nghia/Git/basic.md
> +* Một nhánh trong Git đơn thuần là một con trỏ có khả năng di chuyển được, trỏ đến một trong những commit này. Tên nhánh mặc định của Git là master. Như trong những lần commit đầu tiên, chúng đều đượ
vâng. để em ghi lại cho rõ :)))

2017-09-01 09:27 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +    ![Hình minh hoạ](images/img_2.png)
Ok, vậy anh nghĩ em ghi rõ tiêu đề phần này là cấu trúc của 1 commit thì sẽ rõ ràng hơn

2017-09-01 09:34 UTC, haminhcong commented on K59/Duong-Trung-Nghia/Git/basic.md
> +    ![Hình minh hoạ](images/img_2.png)
2. Nếu em ghi tiêu đề là cấu trúc của 1 commit thì phần nội dung nên tập trung vào đối tượng mà em nói tới là commit

2017-09-02 18:59 UTC, hieulq commented
@nghiadt16 nghỉ lễ đi em

2017-09-02 19:05 UTC, haminhcong commented
@hieulq Em thấy ổn rồi anh ạ, Anh merge cho Nghĩa cái pull request này đi.

2017-09-02 19:09 UTC, hieulq commented
ok done.
good works!

2017-09-02 19:09 UTC, merged